# Development Feature Service docker deployment
# Feature service image is built and deployed
feature-service:
  build: .
  ports:
    - "80:8080"
    - "81:8081"
  volumes:
    - ${PWD}/config:/config
  links:
    - featuredb
  restart: always

featuredb:
  image: mysql:5.7
  environment:
    MYSQL_DATABASE: feature
    MYSQL_ROOT_PASSWORD: supersecretpwd

