# Production Feature Service docker deployment
service-feature:
  image: nmdpbioinformatics/feature-service:1.0-SNAPSHOT
  ports:
    - "80:8080"
    - "81:8081"
  volumes:
    - ./prod-config:/config
  restart: always
  command: "/config/rds.yml"

feature-tools:
  image: nginx
  ports:
    - "8080:80"
  volumes:
    - ./tools-web:/usr/share/nginx/html:ro
  restart: always

